services:
  nginx:
    container_name: nginx
    build:
      context : nginx/.
    image: nginx
    ports:
      - "443:443"
    depends_on:
      - wordpress
      - mariadb
    volumes:
      - wordpress:/var/www/html
    networks:
      - inception
    env_file:
      - .env
    restart: on-failure
  wordpress:
    container_name: wordpress
    build:
      context : wordpress/.
    image: wordpress
    depends_on:
      - "mariadb"
    volumes:
      - wordpress:/var/www/html
      - ./env:/var/www/html/.env
    env_file:
      - .env
    networks:
      - inception
    restart: on-failure
  mariadb:
    container_name: mariadb
    build:
      context : mariadb/.
    image: mariadb
    volumes:
      - mariadb:/var/lib/mysql
    environment:
      WP_URL: "localhost"
    env_file:
      - .env
    networks:
      - inception
    restart: on-failure

volumes:
        wordpress:
                name: wordpress
                driver: local
                driver_opts:
                        device: /home/ashirzad42/inception/wordpress
                        o: bind
                        type: none
        mariadb:
                name: mariadb
                driver: local
                driver_opts:
                        device: /home/ashirzad42/inception/mariadb
                        o: bind
                        type: none

networks:
  inception:
    name: inception

